# syntax=docker/dockerfile:1

# Verwenden Sie ein offizielles Python-Image als Basis
FROM python:3.9-slim

# Setzen Sie das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopieren Sie die Datei requirements.txt in das Arbeitsverzeichnis
COPY requirements.txt requirements.txt

# Installieren Sie die Python-Abhängigkeiten
RUN pip3 install -r requirements.txt

# Kopieren Sie den Rest der Anwendung in das Arbeitsverzeichnis
COPY . .

# Definieren Sie den Befehl zum Ausführen der Anwendung
CMD ["python3", "app.py"]
